apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "etcd-kubernetes-resources-count-exporter.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      etcd:
        endpoints: {{ .Values.etcd.endpoints }}
        cacertpath: "{{ .Values.etcd.cacertpath }}"
        certpath: "{{ .Values.etcd.certpath }}"
        keypath: "{{ .Values.etcd.keypath }}"
        dialtimeout: "{{ .Values.etcd.dialtimeout }}"
        prefix: "{{ .Values.etcd.prefix }}"
