apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    {{- include "etcd-kubernetes-resources-count-exporter.labels" . | nindent 4 }}
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
spec:
  namespaceSelector:
    matchNames:
    - {{ tpl .Values.resource.default.namespace  . }}
  podMetricsEndpoints:
  - port: http
  selector:
    matchLabels:
      {{- include "etcd-kubernetes-resources-count-exporter.selectorLabels" . | nindent 6 }}
