apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ tpl .Values.resource.psp.name . }}
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
  labels:
    {{- include "etcd-kubernetes-resources-count-exporter.labels" . | nindent 4 }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'secret'
    - 'configMap'
    - 'hostPath'
  allowPrivilegeEscalation: false
  hostNetwork: true
  hostIPC: false
  hostPID: false
  hostPorts:
    - min: {{ .Values.listenPort }}
      max: {{ .Values.listenPort }}
