apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name  . }}
  namespace: {{ tpl .Values.resource.default.namespace  . }}
  labels:
    {{- include "etcd-kubernetes-resources-count-exporter.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    giantswarm.io/monitoring: "true"
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    {{- include "etcd-kubernetes-resources-count-exporter.selectorLabels" . | nindent 4 }}
